### ISSUE TITLE
Any guidance on how to create a coherence image

### ISSUE THREAD

**Issue by DenizCanELCI** [olliestephenson/dpm-rnn-public#3]
Hello,
I am trying to run the program but I dont have a coherence image.
Could you provide guidance on how to create a it as you mentioned by "isce" repo?

**Comment by olliestephenson** [comment]
Unfortunately creating the coherence images isn’t straightforward. Assuming that you want to use Sentinel 1 data, you can download it and process the data using the InSAR Scientific Computing Environment (ISCE). You can find more information on that here: https://github.com/isce-framework/isce2/blob/main/contrib/stack/topsStack/README.md (see section 4.4 "stack of correlation" - correlation is the same as coherence).

For a general introduction to ISCE, see the main repo here: https://github.com/isce-framework/isce2/tree/main.
________________________________
From: Deniz Can ELCI ***@***.***>
Sent: Thursday, December 14, 2023 6:59:09 AM
To: olliestephenson/dpm-rnn-public ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [olliestephenson/dpm-rnn-public] Any guidance on how to create a coherence image (Issue #3)


Hello,
I am trying to run the program but I dont have a coherence image.
Could you provide guidance on how to create a it as you mentioned by "isce" repo?
